### ISSUE TITLE
Doesn't fully work w/ Java 9

### ISSUE THREAD

**Issue by xiongtx** [StevenGBrown/javadoc-search-frame#16]
## Problem

For [Java 9 Javadocs](https://docs.oracle.com/javase/9/docs/api/index.html?overview-summary.html), only _some_ packages, interfaces, etc. are shown. In particular, it seems to stop at the letter `B`.

E.g.

![image](https://user-images.githubusercontent.com/1624090/34139150-f807aa24-e427-11e7-9935-2ca452ba622e.png)

## Info

```
Javadoc Search Frame 1.6.3
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Darwin C02RW05YFVH6 15.6.0 (OSX El Capitan)
```

**Comment by StevenGBrown** [comment]
It seems to be working for me. Could you let me know:
- Which version of Javadoc Search Frame you have (you can see this in the browser console)
- Which browser and OS you are using

Maybe the page didn't load fully... does it work if you refresh?

**Comment by xiongtx** [comment]
Filled in some info.

Seems it failed to load properly the first time, then continue to serve what I presume is a cached value until I cleared my cache. Good news is it works great now 😁.

It's a rare occurrence, but maybe worth putting into an FAQ?
